# Generated by Django 5.0.4 on 2024-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProjek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=200)),
            ],
        ),
    ]
