# Generated by Django 5.0.4 on 2024-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0003_alter_refiningresult_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprojek',
            name='id_proyek',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='refiningresult',
            name='refining_result',
            field=models.FileField(upload_to='refining_results/'),
        ),
        migrations.AlterField(
            model_name='trainingtestingresult',
            name='testing_result',
            field=models.FileField(upload_to='testing_results/'),
        ),
        migrations.AlterField(
            model_name='trainingtestingresult',
            name='training_result',
            field=models.FileField(upload_to='training_results/'),
        ),
    ]
