# Generated by Django 5.0.4 on 2024-07-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0005_remove_dataprojek_id_proyek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pek', models.CharField(max_length=100)),
            ],
        ),
    ]
