# Generated by Django 5.0.4 on 2024-07-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0007_rename_nama_pek_pekerjaan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refiningresult',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.modelplanning'),
        ),
        migrations.AlterField(
            model_name='trainingtestingresult',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.modelplanning'),
        ),
    ]
